# Generated by Django 5.2.8 on 2026-01-23 07:51

import common.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG description')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('is_navbar', models.BooleanField(default=False, verbose_name='В меню')),
            ],
            options={
                'verbose_name': 'Простая страница',
                'verbose_name_plural': 'Простые страницы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('contact_type', models.CharField(choices=[('receiver', 'Телефон'), ('mail', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'ВКонтакте'), ('link-external', 'Ссылка'), ('location', 'Адрес')], db_index=True, max_length=20, verbose_name='Тип')),
                ('value', models.CharField(help_text='Например: +79991234567 / email@site.ru / username / https://t.me/username', max_length=255, verbose_name='Значение')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('sort_order', 'title'),
                'indexes': [models.Index(fields=['contact_type'], name='core_contac_contact_340f61_idx'), models.Index(fields=['sort_order'], name='core_contac_sort_or_06ae77_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Город')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta keywords')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG description')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Грузовик'), ('trailer', 'Прицеп'), ('semi_trailer', 'Полуприцеп'), ('special', 'Спецтехника'), ('other', 'Другое')], db_index=True, default='truck', max_length=32, verbose_name='Тип техники')),
                ('engine_type', models.CharField(blank=True, choices=[('diesel', 'Дизель'), ('petrol', 'Бензин'), ('gas', 'Газ'), ('electric', 'Электро'), ('hybrid', 'Гибрид'), ('other', 'Другое')], max_length=20, verbose_name='Тип двигателя')),
                ('vin', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='VIN')),
                ('mileage_km', models.PositiveIntegerField(default=0, verbose_name='Пробег, км')),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Вариатор'), ('other', 'Другое')], max_length=20, verbose_name='Коробка передач')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Год выпуска')),
                ('technical_condition', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('ok', 'Удовлетворительное'), ('needs_repair', 'Требует ремонта')], db_index=True, default='ok', max_length=20, verbose_name='Техническое состояние')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Цвет')),
                ('engine_power_hp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность двигателя, л.с.')),
                ('wheel_formula', models.CharField(blank=True, db_index=True, help_text='Например: 4x2, 6x4, 6x6', max_length=20, verbose_name='Колесная формула')),
                ('price_rub', models.DecimalField(db_index=True, decimal_places=0, max_digits=12, verbose_name='Стоимость, ₽')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наличии'), ('reserved', 'В резерве'), ('sold', 'Продано')], db_index=True, default='in_stock', max_length=20, verbose_name='Статус')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Основное фото')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.brand', verbose_name='Марка')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source', models.CharField(db_index=True, default='site', help_text='Например: site, instagram, avito', max_length=50, verbose_name='Источник')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', common.models.fields.PhoneField(max_length=16, validators=[common.models.fields.validate_phone, common.models.fields.validate_phone], verbose_name='Телефон')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='core.vehicle', verbose_name='Техника')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='core.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ('brand__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='core.vehiclemodel', verbose_name='Модель'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='core_city_region_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='core_vehiclemodel_brand_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type', 'stock_status'], name='core_vehicl_vehicle_dfecc7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='core_vehicl_brand_i_23147d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['city'], name='core_vehicl_city_id_d74814_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year'], name='core_vehicl_year_43064b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price_rub'], name='core_vehicl_price_r_ad06e5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['mileage_km'], name='core_vehicl_mileage_7b9c87_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('vin',), name='core_vehicle_vin_unique_when_not_empty'),
        ),
    ]
