# Generated by Django 5.2.8 on 2026-05-04 14:29

import common.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vehicletype_image_alter_purchaserequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bitrix_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Bitrix ID'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='phone',
            field=common.models.fields.PhoneField(max_length=15, validators=[common.models.fields.validate_phone, common.models.fields.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('awaiting', 'В ожидании поступления'), ('in_stock', 'В наличии'), ('reserved', 'В резерве'), ('sold', 'Продано')], db_index=True, default='in_stock', max_length=20, verbose_name='Статус'),
        ),
    ]
