# Generated by Django 5.2.8 on 2026-05-15 09:22

import common.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_purchaserequest_phone_alter_vehicle_maps_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="phone",
            field=common.models.fields.PhoneField(
                max_length=15,
                validators=[common.models.fields.validate_phone, common.models.fields.validate_phone],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="core.brand",
                verbose_name="Марка",
            ),
        ),
        migrations.AlterField(
            model_name="vehiclemodel",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="core.brand",
                verbose_name="Марка",
            ),
        ),
    ]
