# Generated by Django 5.2.8 on 2026-05-18 10:38

import common.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_purchaserequest_phone_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='phone',
            field=common.models.fields.PhoneField(max_length=15, validators=[common.models.fields.validate_phone, common.models.fields.validate_phone], verbose_name='Телефон'),
        ),
    ]
