# Generated by Django 5.2.8 on 2026-05-26 13:19

import common.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_purchaserequest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='maps_code',
        ),
        migrations.AddField(
            model_name='city',
            name='maps_code',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Код карты'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='phone',
            field=common.models.fields.PhoneField(max_length=15, validators=[common.models.fields.validate_phone, common.models.fields.validate_phone], verbose_name='Телефон'),
        ),
    ]
